# Based on (Jurgens et al 2018)
# pylint: disable=line-too-long
# These include manual lexicons defined by Teufel 2006 and Jurgens 2018
# that help identifying the citation intents.
# They also include linguistic patterns and rules that are leveraged as features for the classifier
# From: Jurgens et al. (2018). Measuring the Evolution of a Scientific Field through Citation Frames.
# Transactions of the Association for Computational Linguistics, 6, 391-406.


ALL_LEXICONS = \
{
    "AFFECT": ["afford","believe","decide","feel","hope","imagine","regard","trust","think"],
    "ARGUMENTATION": ["agree","accept","advocate","argue","claim","conclude","comment","defend","embrace","hypothesize","imply","insist","posit","postulate","reason","recommend","speculate","stipulate","suspect"],
    "AWARE": ["be unaware","be familiar with","be aware","be not aware","know of"],
    "BETTER_SOLUTION": ["boost","enhance","defeat","improve","go beyond","perform better","outperform","outweigh","surpass"],
    "CHANGE": ["adapt","adjust","augment","combine","change","decrease","elaborate","expand","expand on","extend","derive","incorporate","increase","manipulate","modify","optimize","optimise","refine","render","replace","revise","substitute","tailor","upgrade"],
    "COMPARISON": ["compare","compete","evaluate","test"],
    "DENOTATION": ["be","denote","represent"],
    "CONTINUE": ["adopt","base","be base on","base on","derive from","originate in","borrow","build on","follow","following","originate from","originate in","start from","proceed from"],
    "CONTRAST": ["be different from","be distinct from","conflict","contrast","clash","differ from","distinguish","differentiate","disagree","disagreeing","dissent","oppose"],
    "FUTURE_INTEREST": ["be interest in","plan on","plan to","expect to","intend to","hope to"],
    "HEDGING_MODALS": ["could","might","may","should"],
    "INCREASE": ["increase","grow","intensify","build up","explode"],
    "INTEREST": ["aim","ask","address","attempt","be concern","be interest","be motivat","concern","concern","concern","consider","concentrate on","explore","focus","intend to","like to","look at how","pursue","seek","study","try","target","want","wish","wonder"],
    "NEED": ["be dependent on","be reliant on","depend on","lack","need","necessitate","require","rely on"],
    "PRESENTATION": ["describe","discuss","give","introduce","note","notice","point out","present","propose","put forward","recapitulate","remark","report","say","show","sketch","state","suggest","talk about"],
    "PROBLEM": ["abound","aggravate","arise","be cursed","be incapable of","be force to","be limite to","be problematic","be restrict to","be trouble","be unable to","contradict","damage","degrade","degenerate","fail","fall prey","fall short","force","force","hinder","impair","impede","inhibit","misclassify","misjudge","mistake","misuse","neglect","obscure","overestimate","over-estimate","overfit","over-fit","overgeneralize","over-generalize","overgeneralise","over-generalise","overgenerate","over-generate","overlook","pose","plague","preclude","prevent","remain","resort to","restrain","run into","settle for","spoil","suffer from","threaten","thwart","underestimate","under-estimate","undergenerate","under-generate","violate","waste","worsen"],
    "RESEARCH": ["apply","analyze","analyse","build","calculate","categorize","categorise","characterize","characterise","choose","check","classify","collect","compose","compute","conduct","confirm","construct","count","define","delineate","design","detect","determine","equate","estimate","examine","expect","formalize","formalise","formulate","gather","identify","implement","indicate","inspect","integrate","interpret","investigate","isolate","maximize","maximise","measure","minimize","minimise","observe","predict","realize","realise","reconfirm","revalidate","simulate","select","specify","test","verify","work on"],
    "SEE": ["see","view","treat","consider"],
    "SIMILAR": ["bear comparison","be analogous to","be alike","be related to","be closely relate to","be reminiscent of","be the same as","be similar to","be in a similar vein to","have much in common with","have a lot in common with","pattern with","resemble"],
    "SOLUTION": ["accomplish","account for","achieve","apply to","answer","alleviate","allow for","allow","allow","avoid","benefit","capture","clarify","circumvent","contribute","cope with","cover","cure","deal with","demonstrate","develop","devise","discover","elucidate","escape","explain","fix","gain","go a long way","guarantee","handle","help","implement","justify","lend itself","make progress","manage","mend","mitigate","model","obtain","offer","overcome","perform","preserve","prove","provide","realize","realise","rectify","refrain from","remedy","resolve","reveal","scale up","sidestep","solve","succeed","tackle","take care of","take into account","treat","warrant","work well","yield"],
    "TEXTSTRUCTURE": ["begin by","illustrate","conclude by","organize","organise","outline","return to","review","start by","structure","summarize","summarise","turn to"],
    "USE": ["apply","employ","use","make use","utilize","implement","resort to"],
    "NEGATION": ["no","not","nor","non","neither","none","never","aren't","can't","cannot","hadn't","hasn't","haven't","isn't","didn't","don't","doesn't","n't","wasn't","weren't","nothing","nobody","less","least","little","scant","scarcely","rarely","hardly","few","rare","unlikely"],
    "3RD_PERSON_PRONOUN_(NOM)": ["they","he","she","theirs","hers","his"],
    "OTHERS_NOM": ["they","he","she","theirs","hers","his"],
    "3RD_PERSON)PRONOUN_(ACC)": ["her","him","them"],
    "OTHERS_ACC": ["her","him","them"],
    "3RD_POSS_PRONOUN": ["their","his","her"],
    "OTHERS_POSS": ["their","his","her","they"],
    "3RD_PERSON_REFLEXIVE": ["themselves","himself","herself"],
    "1ST_PERSON_PRONOUN_(NOM)": ["we","i","ours","mine"],
    "SELF_NOM": ["we","i","ours","mine"],
    "REFERENTIAL": ["this","that","those","these"],
    "REFLEXIVE": ["itself ourselves","myself","themselves","himself","herself"],
    "QUESTION": ["?","how","why","whether","wonder"],
    "GIVEN": ["noted","mentioned","addressed","illustrated","described","discussed","given","outlined","presented","proposed","reported","shown","taken"],
    "PROFESSIONALS": ["collegues","community","computer scientists","computational linguists","discourse analysts","expert","investigators","linguists","logicians","philosophers","psycholinguists","psychologists","researchers","scholars","semanticists","scientists"],
    "DISCIPLINE": ["computerscience","computer linguistics","computational linguistics","discourse analysis","logics","linguistics","psychology","psycholinguistics","philosophy","semantics","lexical semantics","several disciplines","various disciplines"],
    "TEXT_NOUN": ["paragraph","section","subsection","chapter"],
    "SIMILAR_ADJ": ["similar","comparable","analogous","kindred"],
    "COMPARISON_NOUN": ["accuracy","baseline","comparison","competition","evaluation","inferiority","measure","measurement","performance","precision","optimum","recall","superiority"],
    "CONTRAST_NOUN": ["contrast","conflict","clash","clashes","difference","point of departure"],
    "AIM_NOUN": ["aim","direction","goal","intention","objective","purpose","task","theme","topic"],
    "ARGUMENTATION_NOUN": ["assumption","belief","hypothesis","hypotheses","claim","conclusion","confirmation","opinion","recommendation","stipulation","view"],
    "PROBLEM_NOUN": ["Achilles heel","caveat","challenge","complication","contradiction","damage","danger","deadlock","defect","detriment","difficulty","dilemma","disadvantage","disregard","doubt","downside","drawback","error","failure","fault","foil","flaw","handicap","hindrance","hurdle","ill","inflexibility","impediment","imperfection","intractability","inefficiency","inadequacy","inability","lapse","limitation","malheur","mishap","mischance","mistake","obstacle","oversight","pitfall","problem","shortcoming","threat","trouble","vulnerability","absence","dearth","deprivation","lack","loss","fraught","proliferation","spate"],
    "QUESTION_NOUN": ["question","conundrum","enigma","paradox","phenomena","phenomenon","puzzle","riddle"],
    "SOLUTION_NOUN": ["answer","accomplishment","achievement","advantage","benefit","breakthrough","contribution","explanation","idea","improvement","innovation","insight","justification","proposal","proof","remedy","solution","success","triumph","verification","victory"],
    "RESEARCH_NOUN": ["evidence","experiment","finding","progress","observation","outcome","result"],
    "RESULT_NOUN": ["evidence","experiment","finding","progress","observation","outcome","result"],
    "METRIC_NOUN": ["bleu","F-score","F1-score","F score","F1 score","precision","recall","accuracy","correlation"],
    "CHANGE_NOUN": ["adaptation","enhancement","extension","generalization","development","modification","refinement","version","variant","variation"],
    "PRESENTATION_NOUN": ["article","draft","manuscript","paper","project","report","study"],
    "WORK_NOUN": ["account","algorithm","analysis","analyses","approach","approaches","application","architecture","characterization","characterisation","component","design","extension","formalism","formalization","formalisation","framework","implementation","investigation","machinery","method","methodology","model","module","moduls","process","procedure","program","prototype","research","researches","strategy","system","technique","theory","tool","treatment","work"],
    "TRADITION_NOUN": ["acceptance","community","convention","disciples","disciplines","folklore","literature","mainstream","school","tradition","textbook"],
    "GOOD_ADJ": ["adequate","advantageous","appealing","appropriate","attractive","automatic","beneficial","capable","cheerful","clean","clear","compact","compelling","competitive","comprehensive","consistent","convenient","convincing","constructive","correct","desirable","distinctive","efficient","effective","elegant","encouraging","exact","faultless","favourable","feasible","flawless","good","helpful","impeccable","innovative","insightful","intensive","meaningful","neat","perfect","plausible","positive","polynomial","powerful","practical","preferable","precise","principled","promising","pure","realistic","reasonable","reliable","right","robust","satisfactory","simple","sound","successful","sufficient","systematic","tractable","usable","useful","valid","unlimited","well worked out","well","enough","well-motivated"],
    "BEFORE_ADJ": ["earlier","initial","past","previous","prior"],
    "CONTRAST_ADJ": ["different","distinguishing","contrary","competing","rival"],
    "CONTRAST_ADV": ["differently","distinguishingly","contrarily","otherwise","other than","contrastingly","imcompatibly","on the other hand"],
    "TRADITION_ADJ": ["better known","better-known","cited","classic","common","conventional","current","customary","established","existing","extant","available","favourite","fashionable","general","obvious","long-standing","mainstream","modern","naive","orthodox","popular","prevailing","prevalent","published","quoted","seminal","standard","textbook","traditional","trivial","typical","well-established","well-known","widelyassumed","unanimous","usual"],
    "MANY": ["a number of","a body of","a substantial number of","a substantial body of","most","many","several","various"],
    "HELP_NOUN": ["help","aid","assistance","support"],
    "GRAPHIC_NOUN": ["table","tab","figure","fig","example"],
    "COMPARISON_ADJ": ["evaluative","superior","inferior","optimal","better","best","worse","worst","greater","larger","faster","weaker","stronger"],
    "PROBLEM_ADJ": ["demanding","difficult","hard","non-trivial","nontrivial"],
    "RESEARCH_ADJ": ["empirical","experimental","exploratory","ongoing","quantitative","qualitative","preliminary","statistical","underway"],
    "AWARE_ADJ": ["unnoticed","understood","unexplored"],
    "NEED_ADJ": ["necessary","indispensable","requisite"],
    "NEW_ADJ": ["new","novel","state-of-the-art","state of the art","leading-edge","leading edge","enhanced"],
    "HEDGE_ADJ": ["possible","potential","conceivable","viable"],
    "MAIN_ADJ": ["main","key","basic","central","crucial","critical","essential","eventual","fundamental","great","important","key","largest","main","major","overall","primary","principle","serious","substantial","ultimate"],
    "CURRENT_ADV": ["currently","presently","at present"],
    "TEMPORAL_ADV": ["finally","briefly","next"],
    "STARSEM_NEGATION": ["contrary","without","n't","none","nor","nothing","nowhere","refused","nobody","means","never","neither","absence","except","rather","no","for","fail","not","neglected","less","prevent"],
    "DOWNTONERS": ["almost","barely","hardly","merely","mildly","nearly","only","partially","partly","practically","scarcely","slightly","somewhat"],
    "AMPLIFIERS": ["absolutely","altogether","completely","enormously","entirely","extremely","fully","greatly","highly","intensely","strongly","thoroughly","totally","utterly","very"],
    "PUBLIC_VERBS": ["acknowledge","admit","agree","assert","claim","complain","declare","deny","explain","hint","insist","mention","proclaim","promise","protest","remark","reply","report","say","suggest","swear","write"],
    "PRIVATE_VERBS": ["anticipate","assume","believe","conclude","decide","demonstrate","determine","discover","doubt","estimate","fear","feel","find","forget","guess","hear","hope","imagine","imply","indicate","infer","know","learn","mean","notice","prove","realize","recognize","remember","reveal","see","show","suppose","think","understand"],
    "SUASIVE_VERBS": ["agree","arrange","ask","beg","command","decide","demand","grant","insist","instruct","ordain","pledge","pronounce","propose","recommend","request","stipulate","suggest","urge"]
}

ALL_ACTION_LEXICONS = {
    "AFFECT": ["afford", "believe", "decide", "feel", "hope", "imagine", "regard", "trust", "think"],
    "ARGUMENTATION": ["agree", "accept", "advocate", "argue", "claim", "conclude", "comment", "defend", "embrace", "hypothesize", "imply", "insist", "posit", "postulate", "reason", "recommend", "speculate", "stipulate", "suspect"],
    "AWARE": ["be unaware", "be familiar with", "be aware", "be not aware", "know of"],
    "BETTER_SOLUTION": ["boost", "enhance", "defeat", "improve", "go beyond", "perform better", "outperform", "outweigh", "surpass"],
    "CHANGE": ["adapt", "adjust", "augment", "combine", "change", "decrease", "elaborate", "expand", "expand on", "extend", "derive", "incorporate", "increase", "manipulate", "modify", "optimize", "optimise", "refine", "render", "replace", "revise", "substitute", "tailor", "upgrade"],
    "COMPARISON": ["compare", "compete", "evaluate", "test"],
    "DENOTATION": ["be", "denote", "represent"],
    "INSPIRATION": ["inspire", "motivate"],
    "AGREE": ["agree with", "side with"],
    "CONTINUE": ["adopt", "base", "be base on", 'base on', "derive from", "originate in", "borrow", "build on", "follow", "following", "originate from", "originate in", 'start from', 'proceed from'],
    "CONTRAST": ["be different from", "be distinct from", "conflict", "contrast", "clash", "differ from", "distinguish", "differentiate", "disagree", "disagreeing", "dissent", "oppose"],
    "FUTURE_INTEREST": ["be interest in", "plan on", "plan to", "expect to", "intend to", "hope to"],
    "HEDGING_MODALS": ["could", "might", "may", "should"],
    "FUTURE_MODALS": ["will", "going to"],
    "SHOULD": ["should"],
    "INCREASE": ["increase", "grow", "intensify", "build up", "explode"],
    "INTEREST": ["aim", "ask", "address", "attempt", "be concern", "be interest", "be motivat", "concern", "concern", "concern", "consider", "concentrate on", "explore", "focus", "intend to", "like to", "look at how", "pursue", "seek", "study", "try", "target", "want", "wish", "wonder"],
    "NEED": ["be dependent on", "be reliant on", "depend on", "lack", "need", "necessitate", "require", "rely on"],
    "PRESENTATION": ["describe", "discuss", "give", "introduce", "note", "notice", "point out", "present", "propose", "put forward", "recapitulate", "remark", "report", "say", "show", "sketch", "state", "suggest", "talk about"],
    "PROBLEM": ["abound", "aggravate", "arise", "be cursed", "be incapable of", "be force to", "be limite to", "be problematic", "be restrict to", "be trouble", "be unable to", "contradict", "damage", "degrade", "degenerate", "fail", "fall prey", "fall short", "force", "force", "hinder", "impair", "impede", "inhibit", "misclassify", "misjudge", "mistake", "misuse", "neglect", "obscure", "overestimate", "over-estimate", "overfit", "over-fit", "overgeneralize", "over-generalize", "overgeneralise", "over-generalise", "overgenerate", "over-generate", "overlook", "pose", "plague", "preclude", "prevent", "remain", "resort to", "restrain", "run into", "settle for", "spoil", "suffer from", "threaten", "thwart", "underestimate", "under-estimate", "undergenerate", "under-generate", "violate", "waste", "worsen"],
    "RESEARCH": ["apply", "analyze", "analyse", "build", "calculate", "categorize", "categorise", "characterize", "characterise", "choose", "check", "classify", "collect", "compose", "compute", "conduct", "confirm", "construct", "count", "define", "delineate", "design", "detect", "determine", "equate", "estimate", "examine", "expect", "formalize", "formalise", "formulate", "gather", "identify", "implement", "indicate", "inspect", "integrate", "interpret", "investigate", "isolate", "maximize", "maximise", "measure", "minimize", "minimise", "observe", "predict", "realize", "realise", "reconfirm", "revalidate", "simulate", "select", "specify", "test", "verify", "work on"],
    "SEE": ["see", "view", "treat", "consider"],
    "SIMILAR": ["bear comparison", "be analogous to", "be alike", "be related to", "be closely relate to", "be reminiscent of", "be the same as", "be similar to", "be in a similar vein to", "have much in common with", "have a lot in common with", "pattern with", "resemble"],
    "SOLUTION": ["accomplish", "account for", "achieve", "apply to", "answer", "alleviate", "allow for", "allow", "allow", "avoid", "benefit", "capture", "clarify", "circumvent", "contribute", "cope with", "cover", "cure", "deal with", "demonstrate", "develop", "devise", "discover", "elucidate", "escape", "explain", "fix", "gain", "go a long way", "guarantee", "handle", "help", "implement", "justify", "lend itself", "make progress", "manage", "mend", "mitigate", "model", "obtain", "offer", "overcome", "perform", "preserve", "prove", "provide", "realize", "realise", "rectify", "refrain from", "remedy", "resolve", "reveal", "scale up", "sidestep", "solve", "succeed", "tackle", "take care of", "take into account", "treat", "warrant", "work well", "yield"],
    "TEXTSTRUCTURE": ["begin by", "illustrate", "conclude by", "organize", "organise", "outline", "return to", "review", "start by", "structure", "summarize", "summarise", "turn to"],
    "USE": ["apply", "employ", "use", "make use", "utilize", "implement", 'resort to']
}
ALL_CONCEPT_LEXICONS = {
    "NEGATION": ["no", "not", "nor", "non", "neither", "none", "never", "aren't", "can't", "cannot", "hadn't", "hasn't", "haven't", "isn't", "didn't", "don't", "doesn't", "n't", "wasn't", "weren't", "nothing", "nobody", "less", "least", "little", "scant", "scarcely", "rarely", "hardly", "few", "rare", "unlikely"],
    "3RD_PERSON_PRONOUN_(NOM)": ["they", "he", "she", "theirs", "hers", "his"],
    "OTHERS_NOM": ["they", "he", "she", "theirs", "hers", "his"],
    "3RD_PERSON)PRONOUN_(ACC)": ["her", "him", "them"],
    "OTHERS_ACC": ["her", "him", "them"],
    "3RD_POSS_PRONOUN": ["their", "his", "her"],
    # "OTHERS_POSS": ["their", "his", "her"],
    "OTHERS_POSS": ["their", "his", "her", "they"],
    "3RD_PERSON_REFLEXIVE": ["themselves", "himself", "herself"],
    "1ST_PERSON_PRONOUN_(NOM)": ["we", "i", "ours", "mine"],
    "SELF_NOM": ["we", "i", "ours", "mine"],
    "1ST_PERSON_PRONOUN_(ACC)": ["us", "me"],
    "SELF_ACC": ["us", "me"],
    "1ST_POSS_PRONOUN": ["my", "our"],
    "SELF_POSS": ["my", "our"],
    "1ST_PERSON_REFLEXIVE ": ["ourselves", "myself"],
    "REFERENTIAL": ["this", "that", "those", "these"],
    "REFLEXIVE": ["itself ourselves", "myself", "themselves", "himself", "herself"],
    "QUESTION": ["?", "how", "why", "whether", "wonder"],
    "GIVEN": ["noted", "mentioned", "addressed", "illustrated", "described", "discussed", "given", "outlined", "presented", "proposed", "reported", "shown", "taken"],
    "PROFESSIONALS": ["collegues", "community", "computer scientists", "computational linguists", "discourse analysts", "expert", "investigators", "linguists", "logicians", "philosophers", "psycholinguists", "psychologists", "researchers", "scholars", "semanticists", "scientists"],
    "DISCIPLINE": ["computerscience", "computer linguistics", "computational linguistics", "discourse analysis", "logics", "linguistics", "psychology", "psycholinguistics", "philosophy", "semantics", "lexical semantics", "several disciplines", "various disciplines"],
    "TEXT_NOUN": ["paragraph", "section", "subsection", "chapter"],
    "SIMILAR_NOUN": ["analogy", "similarity"],
    "SIMILAR_ADJ": ["similar", "comparable", "analogous", "kindred"],
    "COMPARISON_NOUN": ["accuracy", "baseline", "comparison", "competition", "evaluation", "inferiority", "measure", "measurement", "performance", "precision", "optimum", "recall", "superiority"],
    "CONTRAST_NOUN": ["contrast", "conflict", "clash", "clashes", "difference", "point of departure"],
    "AIM_NOUN": ["aim", "direction", "goal", "intention", "objective", "purpose", "task", "theme", "topic"],
    "ARGUMENTATION_NOUN": ["assumption", "belief", "hypothesis", "hypotheses", "claim", "conclusion", "confirmation", "opinion", "recommendation", "stipulation", "view"],
    "PROBLEM_NOUN": ["Achilles heel", "caveat", "challenge", "complication", "contradiction", "damage", "danger", "deadlock", "defect", "detriment", "difficulty", "dilemma", "disadvantage", "disregard", "doubt", "downside", "drawback", "error", "failure", "fault", "foil", "flaw", "handicap", "hindrance", "hurdle", "ill", "inflexibility", "impediment", "imperfection", "intractability", "inefficiency", "inadequacy", "inability", "lapse", "limitation", "malheur", "mishap", "mischance", "mistake", "obstacle", "oversight", "pitfall", "problem", "shortcoming", "threat", "trouble", "vulnerability", "absence", "dearth", "deprivation", "lack", "loss", "fraught", "proliferation", "spate"],
    "QUESTION_NOUN": ["question", "conundrum", "enigma", "paradox", "phenomena", "phenomenon", "puzzle", "riddle"],
    "SOLUTION_NOUN": ["answer", "accomplishment", "achievement", "advantage", "benefit", "breakthrough", "contribution", "explanation", "idea", "improvement", "innovation", "insight", "justification", "proposal", "proof", "remedy", "solution", "success", "triumph", "verification", "victory"],
    "INTEREST_NOUN": ["attention", "quest"],
    # Not sure if this one is used
    "RESEARCH_NOUN": ["evidence", "experiment", "finding", "progress", "observation", "outcome", "result"],
    "RESULT_NOUN": ["evidence", "experiment", "finding", "progress", "observation", "outcome", "result"],
    "METRIC_NOUN": ["bleu", "F-score", "F1-score", "F score", "F1 score", "precision", "recall", "accuracy", "correlation"],
    "CHANGE_NOUN": ["adaptation", "enhancement", "extension", "generalization", "development", "modification", "refinement", "version", "variant", "variation"],
    "PRESENTATION_NOUN": ["article", "draft", "manuscript", "paper", "project", "report", "study"],
    "NEED_NOUN": ["necessity", "motivation"],
    "WORK_NOUN": ["account", "algorithm", "analysis", "analyses", "approach", "approaches", "application", "architecture", "characterization", "characterisation", "component", "design", "extension", "formalism", "formalization", "formalisation", "framework", "implementation", "investigation", "machinery", "method", "methodology", "model", "module", "moduls", "process", "procedure", "program", "prototype", "research", "researches", "strategy", "system", "technique", "theory", "tool", "treatment", "work"],
    "TRADITION_NOUN": ["acceptance", "community", "convention", "disciples", "disciplines", "folklore", "literature", "mainstream", "school", "tradition", "textbook"],
    "CHANGE_ADJ": ["alternate", "alternative"],
    "GOOD_ADJ": ["adequate", "advantageous", "appealing", "appropriate", "attractive", "automatic", "beneficial", "capable", "cheerful", "clean", "clear", "compact", "compelling", "competitive", "comprehensive", "consistent", "convenient", "convincing", "constructive", "correct", "desirable", "distinctive", "efficient", "effective", "elegant", "encouraging", "exact", "faultless", "favourable", "feasible", "flawless", "good", "helpful", "impeccable", "innovative", "insightful", "intensive", "meaningful", "neat", "perfect", "plausible", "positive", "polynomial", "powerful", "practical", "preferable", "precise", "principled", "promising", "pure", "realistic", "reasonable", "reliable", "right", "robust", "satisfactory", "simple", "sound", "successful", "sufficient", "systematic", "tractable", "usable", "useful", "valid", "unlimited", "well worked out", "well", "enough", "well-motivated"],
    "BAD_ADJ": ["absent", "ad-hoc", "adhoc", "ad hoc", "annoying", "ambiguous", "arbitrary", "awkward", "bad", "brittle", "brute-force", "brute force", "careless", "confounding", "contradictory", "defect", "defunct", "disturbing", "elusive", "erraneous", "expensive", "exponential", "false", "fallacious", "frustrating", "haphazard", "ill-defined", "imperfect", "impossible", "impractical", "imprecise", "inaccurate", "inadequate", "inappropriate", "incomplete", "incomprehensible", "inconclusive", "incorrect", "inelegant", "inefficient", "inexact", "infeasible", "infelicitous", "inflexible", "implausible", "inpracticable", "improper", "insufficient", "intractable", "invalid", "irrelevant", "labour-intensive", "laborintensive", "labour intensive", "labor intensive", "laborious", "limited-coverage", "limited coverage", "limited", "limiting", "meaningless", "modest", "misguided", "misleading", "nonexistent", "NP-hard", "NP-complete", "NP hard", "NP complete", "questionable", "pathological", "poor", "prone", "protracted", "restricted", "scarce", "simplistic", "suspect", "time-consuming", "time consuming", "toy", "unacceptable", "unaccounted for", "unaccounted-for", "unaccounted", "unattractive", "unavailable", "unavoidable", "unclear", "uncomfortable", "unexplained", "undecidable", "undesirable", "unfortunate", "uninnovative", "uninterpretable", "unjustified", "unmotivated", "unnatural", "unnecessary", "unorthodox", "unpleasant", "unpractical", "unprincipled", "unreliable", "unsatisfactory", "unsound", "unsuccessful", "unsuited", "unsystematic", "untractable", "unwanted", "unwelcome", "useless", "vulnerable", "weak", "wrong", "too", "overly", "only"],
    "BEFORE_ADJ": ["earlier", "initial", "past", "previous", "prior"],
    "CONTRAST_ADJ": ["different", "distinguishing", "contrary", "competing", "rival"],
    "CONTRAST_ADV": ["differently", "distinguishingly", "contrarily", "otherwise", "other than", "contrastingly", "imcompatibly", "on the other hand", ],
    "TRADITION_ADJ": ["better known", "better-known", "cited", "classic", "common", "conventional", "current", "customary", "established", "existing", "extant", "available", "favourite", "fashionable", "general", "obvious", "long-standing", "mainstream", "modern", "naive", "orthodox", "popular", "prevailing", "prevalent", "published", "quoted", "seminal", "standard", "textbook", "traditional", "trivial", "typical", "well-established", "well-known", "widelyassumed", "unanimous", "usual"],
    "MANY": ["a number of", "a body of", "a substantial number of", "a substantial body of", "most", "many", "several", "various"],
    "HELP_NOUN": ['help', 'aid', 'assistance', 'support'],
    "SENSE_NOUN": ['sense', 'spirit', ],
    "GRAPHIC_NOUN": ['table', 'tab', 'figure', 'fig', 'example'],
    "COMPARISON_ADJ": ["evaluative", "superior", "inferior", "optimal", "better", "best", "worse", "worst", "greater", "larger", "faster", "weaker", "stronger"],
    "PROBLEM_ADJ": ["demanding", "difficult", "hard", "non-trivial", "nontrivial"],
    "RESEARCH_ADJ": ["empirical", "experimental", "exploratory", "ongoing", "quantitative", "qualitative", "preliminary", "statistical", "underway"],
    "AWARE_ADJ": ["unnoticed", "understood", "unexplored"],
    "NEED_ADJ": ["necessary", "indispensable", "requisite"],
    "NEW_ADJ": ["new", "novel", "state-of-the-art", "state of the art", "leading-edge", "leading edge", "enhanced"],
    "FUTURE_ADJ": ["further", "future"],
    "HEDGE_ADJ": ["possible", "potential", "conceivable", "viable"],
    "MAIN_ADJ": ["main", "key", "basic", "central", "crucial", "critical", "essential", "eventual", "fundamental", "great", "important", "key", "largest", "main", "major", "overall", "primary", "principle", "serious", "substantial", "ultimate"],
    "CURRENT_ADV": ["currently", "presently", "at present"],
    "TEMPORAL_ADV": ["finally", "briefly", "next"],
    # "SPECULATION": [],
    # "CONTRARY": [],
    # "SUBJECTIVITY": [],
    "STARSEM_NEGATION": ["contrary", "without", "n't", "none", "nor", "nothing", "nowhere", "refused", "nobody", "means", "never", "neither", "absence", "except", "rather", "no", "for", "fail", "not", "neglected", "less", "prevent",
                         ],
    'DOWNTONERS': ['almost', 'barely', 'hardly', 'merely', 'mildly', 'nearly', 'only', 'partially', 'partly', 'practically', 'scarcely', 'slightly', 'somewhat', ],
    'AMPLIFIERS': ['absolutely', 'altogether', 'completely', 'enormously', 'entirely', 'extremely', 'fully', 'greatly', 'highly', 'intensely', 'strongly', 'thoroughly', 'totally', 'utterly', 'very', ],
    'PUBLIC_VERBS': ['acknowledge', 'admit', 'agree', 'assert', 'claim', 'complain', 'declare', 'deny', 'explain', 'hint', 'insist', 'mention', 'proclaim', 'promise', 'protest', 'remark', 'reply', 'report', 'say', 'suggest', 'swear', 'write', ],
    'PRIVATE_VERBS': ['anticipate', 'assume', 'believe', 'conclude', 'decide', 'demonstrate', 'determine', 'discover', 'doubt', 'estimate', 'fear', 'feel', 'find', 'forget', 'guess', 'hear', 'hope', 'imagine', 'imply', 'indicate', 'infer', 'know', 'learn', 'mean', 'notice', 'prove', 'realize', 'recognize', 'remember', 'reveal', 'see', 'show', 'suppose', 'think', 'understand', ],
    'SUASIVE_VERBS': ['agree', 'arrange', 'ask', 'beg', 'command', 'decide', 'demand', 'grant', 'insist', 'instruct', 'ordain', 'pledge', 'pronounce', 'propose', 'recommend', 'request', 'stipulate', 'suggest', 'urge', ]
}


FORMULAIC_PATTERNS = {
    "GENERAL_FORMULAIC": ["in @TRADITION_ADJ #JJ @WORK_NOUN",
                          "in @TRADITION_ADJ used @WORK_NOUN",
                          "in @TRADITION_ADJ @WORK_NOUN",
                          "in @MANY #JJ @WORK_NOUN",
                          "in @MANY @WORK_NOUN",
                          "in @BEFORE_ADJ #JJ @WORK_NOUN",
                          "in @BEFORE_ADJ @WORK_NOUN",
                          "in other #JJ @WORK_NOUN",
                          #"in other @WORK_NOUN",
                          "in such @WORK_NOUN"
                          ],

    "THEM_FORMULAIC": ["according to CITATION",
                       "like CITATION",
                       "such as CITATION",
                       "CITATION style",
                       "a la CITATION",
                       "CITATION - style"],

    "US_PREVIOUS_FORMULAIC": ["@SELF_NOM have previously",
                              "@SELF_NOM have earlier"
                              "@SELF_NOM have elsewhere",
                              "@SELF_NOM elsewhere",
                              "@SELF_NOM previously",
                              "@SELF_NOM earlier",
                              "elsewhere @SELF_NOM",
                              "elswhere @SELF_NOM",
                              "elsewhere , @SELF_NOM",
                              "elswhere , @SELF_NOM",
                              "presented elswhere",
                              "presented elsewhere",
                              "@SELF_NOM have @ARGUMENTATION elsewhere",
                              "@SELF_NOM have @SOLUTION elsewhere",
                              "@SELF_NOM have argue elsewhere",
                              "@SELF_NOM have show elswhere_NOM",
                              "@SELF_NOM have argue elswhere_NOM",
                              "@SELF_NOM will show elsewhere",
                              "@SELF_NOM will show elswhere",
                              "@SELF_NOM will argue elsewhere",
                              "@SELF_NOM will argue elswhere",
                              "elsewhere SELFCITE",
                              "elswhere SELFCITE",
                              "in a @BEFORE_ADJ @PRESENTATION_NOUN",
                              "in an earlier @PRESENTATION_NOUN",
                              "another @PRESENTATION_NOUN"],

    "TEXTSTRUCTURE_FORMULAIC": ["then @SELF_NOM describe",
                                "then , @SELF_NOM describe",
                                "next @SELF_NOM describe",
                                "next , @SELF_NOM describe",
                                "finally @SELF_NOM describe",
                                "finally , @SELF_NOM describe",
                                "then @SELF_NOM present",
                                "then , @SELF_NOM present",
                                "next @SELF_NOM present",
                                "next , @SELF_NOM present",
                                "finally @SELF_NOM present",
                                "finally , @SELF_NOM present",
                                "briefly describe",
                                "briefly introduce",
                                "briefly present",
                                "briefly discuss"],

    "HERE_FORMULAIC": ["in this @PRESENTATION_NOUN",
                       "the present @PRESENTATION_NOUN",
                       "@SELF_NOM here",
                       "here @SELF_NOM",
                       "here , @SELF_NOM",
                       "@GIVEN here",
                       "@SELF_NOM now",
                       "now @SELF_NOM",
                       "now , @SELF_NOM",
                       "@GIVEN now",
                       "herein"],

    "METHOD_FORMULAIC": ["a new @WORK_NOUN",
                         "a novel @WORK_NOUN",
                         "a @WORK_NOUN of",
                         "an @WORK_NOUN of",
                         "a #JJ @WORK_NOUN of",
                         "an #JJ @WORK_NOUN of",
                         "a #NN @WORK_NOUN of",
                         "an #NN @WORK_NOUN of",
                         "a #JJ #NN @WORK_NOUN of",
                         "an #JJ #NN @WORK_NOUN of",
                         "a @WORK_NOUN for",
                         "an @WORK_NOUN for",
                         "a #JJ @WORK_NOUN for",
                         "an #JJ @WORK_NOUN for",
                         "a #NN @WORK_NOUN for",
                         "an #NN @WORK_NOUN for",
                         "a #JJ #NN @WORK_NOUN for",
                         "an #JJ #NN @WORK_NOUN for",
                         "@WORK_NOUN design to #VV",  # diff
                         "@WORK_NOUN intend for",
                         "@WORK_NOUN for #VV",
                         "@WORK_NOUN for the #NN",
                         "@WORK_NOUN design to #VV",  # diff
                         "@WORK_NOUN to the #NN",
                         "@WORK_NOUN to #NN",
                         "@WORK_NOUN to #VV",
                         "@WORK_NOUN for #JJ #VV",  # diff
                         "@WORK_NOUN for the #JJ #NN,"
                         "@WORK_NOUN to the #JJ #NN",
                         "@WORK_NOUN to #JJ #VV",
                         "the problem of #RB #VV",
                         "the problem of #VV",  # diff
                         "the problem of how to"],

    "CONTINUE_FORMULAIC": ["follow CITATION",
                           "follow the @WORK_NOUN of CITATION",
                           "follow the @WORK_NOUN give in CITATION",
                           "follow the @WORK_NOUN present in CITATION",
                           "follow the @WORK_NOUN propose in CITATION",
                           "follow the @WORK_NOUN discuss in CITATION",
                           "base on CITATION",
                           "@CONTINUE CITATION",
                           "@CONTINUE the @WORK_NOUN",
                           "@CONTINUE a @WORK_NOUN",
                           "@CONTINUE an @WORK_NOUN",
                           "@CONTINUE @OTHERS_POSS @WORK_NOUN",
                           "@CONTINUE @SELF_POSS @WORK_NOUN",
                           "@AGREE CITATION",
                           "@AGREE the @WORK_NOUN",
                           "@AGREE a @WORK_NOUN",
                           "@AGREE an @WORK_NOUN",
                           "@AGREE @OTHERS_POSS @WORK_NOUN",
                           "@AGREE @SELF_POSS @WORK_NOUN",
                           "base on the @WORK_NOUN of CITATION",
                           "base on the @WORK_NOUN give in CITATION",
                           "base on the @WORK_NOUN present in CITATION",
                           "base on the @WORK_NOUN propose in CITATION",
                           "base on the @WORK_NOUN discuss in CITATION",
                           "adopt CITATION",
                           "start point for @REFERENTIAL @WORK_NOUN",
                           "start point for @SELF_POSS @WORK_NOUN",
                           "as a start point",
                           "as start point",
                           "use CITATION",  # dif
                           "base @SELF_POSS",
                           "support @SELF_POSS",
                           "support @OTHERS_POSS",
                           "lend support to @SELF_POSS",
                           "lend support to @OTHERS_POSS",
                           # new
                           "@CONTINUE the @WORK_NOUN of",
                           "@AGREE the @WORK_NOUN of"
                           ],

    "DISCOURSE_CONTRAST_FORMULAIC": ["however",
                                     #"nevertheless",
                                     #"nonetheless",
                                     "unfortunately",
                                     #"yet",
                                     #"although",
                                     "whereas"
                                     ],

    "GRAPHIC_FORMULAIC": ["@GRAPHIC_NOUN #CD"],

    "CONTRAST2_FORMULAIC": ["this @WORK_NOUN @CONTRAST",
                            "@SELF_POSS @WORK_NOUN @CONTRAST",
                            "this @PRESENTATION_NOUN @CONTRAST",
                            "@SELF_POSS @PRESENTATION_NOUN @CONTRAST",
                            "compare to @OTHERS_POSS @WORK_NOUN",
                            "compare to @OTHERS_POSS @PRESENTATION_NOUN",
                            "@OTHERS_POSS @WORK_NOUN @CONTRAST",
                            "that @WORK_NOUN @CONTRAST",
                            "that @PRESENTATION_NOUN @CONTRAST",
                            "@OTHERS_POSS @PRESENTATION_NOUN @CONTRAST",
                            ],

    "COMPARISON_FORMULAIC": ["in @COMPARISON with",
                             "in @COMPARISON to",
                             "@GIVEN #NN @SIMILAR",
                             "@SELF_POSS #NN @SIMILAR",
                             "@SELF_POSS @PRESENTATION @SIMILAR",
                             "a @SELF_POSS @PRESENTATION @SIMILAR",
                             "a @SIMILAR_ADJ @WORK_NOUN is",
                             "be closely relate to",
                             "be @SIMILAR_ADJ to",
                             "along the line of CITATION",
                             ],

    "CONTRAST_FORMULAIC": ["against CITATATION",
                           "against @SELF_ACC",
                           "against @SELF_POSS",
                           "against @OTHERS_ACC",
                           "against @OTHERS_POSS",
                           "against @BEFORE_ADJ @WORK_NOUN",
                           "against @MANY @WORK_NOUN",
                           "against @TRADITION_ADJ @WORK_NOUN",
                           "than CITATATION",
                           "than @SELF_ACC",
                           "than @SELF_POSS",
                           "than @OTHERS_ACC",
                           "than @OTHERS_POSS",
                           "than @TRADITION_ADJ @WORK_NOUN",
                           "than @BEFORE_ADJ @WORK_NOUN",
                           "than @MANY @WORK_NOUN",
                           "point of departure from @SELF_POSS",
                           "points of departure from @OTHERS_POSS",
                           "advantage over @OTHERS_ACC",
                           "advantage over @TRADITION_ADJ",
                           "advantage over @MANY @WORK_NOUN",
                           "advantage over @BEFORE_ADJ @WORK_NOUN",
                           "advantage over @OTHERS_POSS",
                           "advantage over CITATATION",
                           "advantage to @OTHERS_ACC",
                           "advantage to @OTHERS_POSS",
                           "advantage to CITATATION",
                           "advantage to @TRADITION_ADJ",
                           "advantage to @MANY @WORK_NOUN",
                           "advantage to @BEFORE_ADJ @WORK_NOUN",
                           "benefit over @OTHERS_ACC",
                           "benefit over @OTHERS_POSS",
                           "benefit over CITATATION",
                           "benefit over @TRADITION_ADJ",
                           "benefit over @MANY @WORK_NOUN",
                           "benefit over @BEFORE_ADJ @WORK_NOUN",
                           "difference to CITATATION",
                           "difference to @TRADITION_ADJ",
                           "difference to CITATATION",
                           "difference to @TRADITION_ADJ",
                           "difference to @MANY @WORK_NOUN",
                           "difference to @BEFORE_ADJ @WORK_NOUN",
                           "difference to @OTHERS_ACC",
                           "difference to @OTHERS_POSS",
                           "difference to @SELF_ACC",
                           "difference to @SELF_POSS",
                           "difference between CITATATION",
                           "difference between @TRADITION_ADJ",
                           "difference between @MANY @WORK_NOUN",
                           "difference between @BEFORE_ADJ @WORK_NOUN",
                           "difference between @OTHERS_ACC",
                           "difference between @OTHERS_POSS",
                           "difference between @SELF_ACC",
                           "difference between @SELF_POSS",
                           "contrast with CITATATION",
                           "contrast with @TRADITION_ADJ",
                           "contrast with @MANY @WORK_NOUN",
                           "contrast with @BEFORE_ADJ @WORK_NOUN",
                           "contrast with @OTHERS_ACC",
                           "contrast with @OTHERS_POSS",
                           "contrast with @SELF_ACC",
                           "contrast with @SELF_POSS",
                           "unlike @SELF_ACC",
                           "unlike @SELF_POSS",
                           "unlike CITATATION",
                           "unlike @TRADITION_ADJ",
                           "unlike @BEFORE_ADJ @WORK_NOUN",
                           "unlike @MANY @WORK_NOUN",
                           "unlike @OTHERS_ACC",
                           "unlike @OTHERS_POSS",
                           "in contrast to @SELF_ACC",
                           "in contrast to @SELF_POSS",
                           "in contrast to CITATATION",
                           "in contrast to @TRADITION_ADJ",
                           "in contrast to @MANY @WORK_NOUN",
                           "in contrast to @BEFORE_ADJ @WORK_NOUN",
                           "in contrast to @OTHERS_ACC",
                           "in contrast to @OTHERS_POSS",
                           "as oppose to @SELF_ACC",
                           "as oppose to @SELF_POSS",
                           "as oppose to CITATATION",
                           "as oppose to @TRADITION_ADJ",
                           "as oppose to @MANY @WORK_NOUN",
                           "as oppose to @BEFORE_ADJ @WORK_NOUN",
                           "as oppose to @OTHERS_ACC",
                           "as oppose to @OTHERS_POSS",
                           "contrary to @SELF_ACC",
                           "contrary to @SELF_POSS",
                           "contrary to CITATATION",
                           "contrary to @TRADITION_ADJ",
                           "contrary to @MANY @WORK_NOUN",
                           "contrary to @BEFORE_ADJ @WORK_NOUN",
                           "contrary to @OTHERS_ACC",
                           "contrary to @OTHERS_POSS",
                           "whereas @SELF_ACC",
                           "whereas @SELF_POSS",
                           "whereas CITATATION",
                           "whereas @TRADITION_ADJ",
                           "whereas @BEFORE_ADJ @WORK_NOUN",
                           "whereas @MANY @WORK_NOUN",
                           "whereas @OTHERS_ACC",
                           "whereas @OTHERS_POSS",
                           "compare to @SELF_ACC",
                           "compare to @SELF_POSS",
                           "compare to CITATATION",
                           #"compare to @TRADITION_ADJ",
                           "compare to @BEFORE_ADJ @WORK_NOUN",
                           "compare to @MANY @WORK_NOUN",
                           "compare to @OTHERS_ACC",
                           "compare to @OTHERS_POSS",
                           "in comparison to @SELF_ACC",
                           "in comparison to @SELF_POSS",
                           "in comparison to CITATATION",
                           "in comparison to @TRADITION_ADJ",
                           "in comparison to @MANY @WORK_NOUN",
                           "in comparison to @BEFORE_ADJ @WORK_NOUN",
                           "in comparison to @OTHERS_ACC",
                           "in comparison to @OTHERS_POSS",
                           "while @SELF_NOM",
                           "while @SELF_POSS",
                           "while CITATATION",
                           "while @TRADITION_ADJ",
                           "while @BEFORE_ADJ @WORK_NOUN",
                           "while @MANY @WORK_NOUN",
                           "while @OTHERS_NOM",
                           "while @OTHERS_POSS",
                           "this @WORK_NOUN @COMPARISON",
                           "@SELF_POSS @WORK_NOUN @COMPARISON",
                           "this @PRESENTATION_NOUN @COMPARISON",
                           "@SELF_POSS @PRESENTATION_NOUN @COMPARISON",
                           "compare to @OTHERS_POSS @WORK_NOUN",
                           "compare to @OTHERS_POSS @PRESENTATION_NOUN",
                           "@OTHERS_POSS @WORK_NOUN @COMPARISON",
                           "that @WORK_NOUN @COMPARISON",
                           "that @PRESENTATION_NOUN @COMPARISON",
                           "@OTHERS_POSS @PRESENTATION_NOUN @COMPARISON",
                           ],
    "ALIGN_FORMULAIC": ["in the @SENSE_NOUN of CITATION"],

    "AFFECT_FORMULAIC": ["hopefully", "thankfully", "fortunately", "unfortunately"],

    "GOOD_FORMULAIC": ["@GOOD_ADJ"],
    #"BAD_FORMULAIC": [ "@BAD_ADJ" ],
    "TRADITION_FORMULAIC": ["@TRADITION_ADJ"],
    "IN_ORDER_TO_FORMULAIC": ["in order to"],

    "DETAIL_FORMULAIC": ["@SELF_NOM have also",
                         "@SELF_NOM also",
                         "this @PRESENTATION_NOUN also",
                         "this @PRESENTATION_NOUN has also"],

    "NO_TEXTSTRUCTURE_FORMULAIC": ["( @TEXT_NOUN CREF )",
                                   "as explain in @TEXT_NOUN CREF",
                                   "as explain in the @BEFORE_ADJ @TEXT_NOUN",
                                   "as @GIVEN early in this @TEXT_NOUN",
                                   "as @GIVEN below",
                                   "as @GIVEN in @TEXT_NOUN CREF",
                                   "as @GIVEN in the @BEFORE_ADJ @TEXT_NOUN",
                                   "as @GIVEN in the next @TEXT_NOUN",
                                   "#NN @GIVEN in @TEXT_NOUN CREF",
                                   "#NN @GIVEN in the @BEFORE_ADJ @TEXT_NOUN",
                                   "#NN @GIVEN in the next @TEXT_NOUN",
                                   "#NN @GIVEN below",
                                   "cf. @TEXT_NOUN CREF",
                                   "cf. @TEXT_NOUN below",
                                   "cf. the @TEXT_NOUN below",
                                   "cf. the @BEFORE_ADJ @TEXT_NOUN",
                                   "cf. @TEXT_NOUN above",
                                   "cf. the @TEXT_NOUN above",
                                   "cfXXX @TEXT_NOUN CREF",
                                   "cfXXX @TEXT_NOUN below",
                                   "cfXXX the @TEXT_NOUN below",
                                   "cfXXX the @BEFORE_ADJ @TEXT_NOUN",
                                   "cfXXX @TEXT_NOUN above",
                                   "cfXXX the @TEXT_NOUN above",
                                   "e. g. , @TEXT_NOUN CREF",
                                   "e. g , @TEXT_NOUN CREF",
                                   "e. g. @TEXT_NOUN CREF",
                                   "e. g @TEXT_NOUN CREF",
                                   "e.g., @TEXT_NOUN CREF",
                                   "e.g. @TEXT_NOUN CREF",
                                   "compare @TEXT_NOUN CREF",
                                   "compare @TEXT_NOUN below",
                                   "compare the @TEXT_NOUN below",
                                   "compare the @BEFORE_ADJ @TEXT_NOUN",
                                   "compare @TEXT_NOUN above",
                                   "compare the @TEXT_NOUN above",
                                   "see @TEXT_NOUN CREF",
                                   "see the @BEFORE_ADJ @TEXT_NOUN",
                                   "recall from the @BEFORE_ADJ @TEXT_NOUN",
                                   "recall from the @TEXT_NOUN above",
                                   "recall from @TEXT_NOUN CREF",
                                   "@SELF_NOM shall see below",
                                   "@SELF_NOM will see below",
                                   "@SELF_NOM shall see in the next @TEXT_NOUN",
                                   "@SELF_NOM will see in the next @TEXT_NOUN",
                                   "@SELF_NOM shall see in @TEXT_NOUN CREF",
                                   "@SELF_NOM will see in @TEXT_NOUN CREF",
                                   "example in @TEXT_NOUN CREF",
                                   "example CREF in @TEXT_NOUN CREF",
                                   "example CREF and CREF in @TEXT_NOUN CREF",
                                   "example in @TEXT_NOUN CREF"],

    "USE_FORMULAIC": ["@SELF_NOM @USE",
                      #"@WORK_NOUN @USE",
                      "@SELF_NOM @RESEARCH",
                      #"be @USE to",
                      #"can be #VV use", #can be /solved/ using
                      #"@SELF_POSS @WORK_NOUN be @CONTINUE",
                      #"@SELF_POSS #JJ @WORK_NOUN be @CONTINUE",
                      "@SOLUTION with the @HELP_NOUN of",
                      "@SOLUTION with the @WORK_NOUN of",
                      ],

    "FUTURE_WORK_FORMULAIC": ["@FUTURE_ADJ @WORK_NOUN",
                              "@FUTURE_ADJ @AIM_NOUN",
                              "@FUTURE_ADJ @CHANGE_NOUN",
                              "a @HEDGE_ADJ @AIM_NOUN",
                              "one @HEDGE_ADJ @AIM_NOUN",
                              "#NN be also @HEDGE_ADJ",
                              "in the future",
                              "@SELF_NOM @FUTURE_INTEREST",
                              ],

    "HEDGING_FORMULAIC": ["@HEDGING_MODALS be @RESEARCH",
                          "@HEDGING_MODALS be @CHANGE",
                          "@HEDGING_MODALS be @SOLUTION",
                          ],

    "PRESENT_WORK_FORMULAIC": ["@SELF_NOM be @CURRENT_ADV @RESEARCH",
                               "@SELF_NOM be @RESEARCH @CURRENT_ADV"],

    "EXTENDING_WORK_FORMULAIC": ["@CHANGE the @WORK_NOUN",
                                 "@CHANGE this @WORK_NOUN",
                                 "@SELF_POSS @WORK_NOUN be @CHANGE",
                                 "@SELF_POSS #JJ @WORK_NOUN be @CHANGE",
                                 "@SELF_POSS @WORK_NOUN @CHANGE",
                                 "@SELF_POSS #JJ @WORK_NOUN @CHANGE",
                                 "@CHANGE the #JJ @WORK_NOUN",
                                 "@SELF_NOM @CHANGE"
                                 ],

    "EXTENDING_WORK2_FORMULAIC": ["@SELF_NOM @CHANGE #DD @WORK_NOUN",
                                  "@SELF_POSS @WORK_NOUN @CHANGE",
                                  "@CHANGE from CITATION",
                                  "@CHANGE from #NN of CITATION",
                                  "@SELF_POSS @CHANGE_NOUN of CITATION",
                                  "@SELF_POSS @WORK_NOUN @CONTINUE",
                                  "@SELF_POSS @WORK_NOUN be #DD @CHANGE_NOUN",
                                  "@SELF_POSS @WORK_NOUN be #VV #DD @CHANGE_NOUN",
                                  "#NN be #DD @CHANGE_NOUN of",
                                  "#NN be #DD #JJ @CHANGE_NOUN of",
                                  "#DD #NN @DENOTATION #DD @CHANGE_NOUN of",
                                  "@TEXT_NOUN @CONTINUE CITATION",
                                  "#NN @CONTINUE #NN of CITATION",
                                  "be @SEE as an @CHANGE_NOUN",
                                  "@CHANGE #DD #NN of CITATION",
                                  ],

    "USEFUL_FORMULAIC": ["have shown @GOOD_ADJ for"],

    "MOTIVATING_FORMULAIC": ["as @PRESENTATION in CITATION",
                             "as @PRESENTATION by CITATION",
                             "this be a #JJ convention",
                             "this be a #RB #JJ convention",
                             "@CONTINUE the #NN result",
                             "@CONTINUE the #JJ result",
                             "@AGREE the #NN result",
                             "@AGREE the #JJ result",

                             #"@INSPRATION by the #NN result",
                             #"@INSPIRATION by the #JJ result",
                             "@INSPIRATION by",
                             "CITATION have @PRESENTATION that",
                             "have remain a @PROBLEM_NOUN",

                             "their importance have @INCREASE",

                             "#NN be @MAIN_ADJ in",
                             "#NN be @MAIN_ADJ for",

                             "it be @MAIN_ADJ not to",

                             "from CITATION , @SELF_NOM",

                             "@CONTINUE CITATION, @SELF_NOM",
                             "@AGREE CITATION, @SELF_NOM",
                             "@RESEARCH in @DISCIPLINE @PRESENTATION",
                             "@RESEARCH in #NN @PRESENTATION",
                             "@RESEARCH in #NN #NN @PRESENTATION",
                             "@RESEARCH in #JJ #NN @PRESENTATION",

                             "negative @RESULT_NOUN for",
                             "negative @RESULT_NOUN that",

                             # "have be @PRESENTATION",  # SUPER NOISY :(
                             "it be well document",
                             "it have be well document",
                             "#NN need to @USE",

                             "CITATION have @RESEARCH it",
                             "CITATION have @PRESENTATION that",
                             "CITATATION @PRESENTATION that",
                             "CITATATION #RB @PRESENTATION that",

                             "prove to be @GOOD_ADJ in",
                             "@PRESENTATION to be @GOOD_ADJ in",
                             "prove to be @GOOD_ADJ for",
                             "@PRESENTATION to be @GOOD_ADJ for",
                             ],

    "PRIOR_WORK_FORMULAIC": ["@BEFORE_ADJ @PRESENTATION @SELF_NOM",
                             "@BEFORE_ADJ @PRESENTATION , @SELF_NOM",
                             "a @BEFORE_ADJ @PRESENTATION @SELF_NOM",
                             "a @BEFORE_ADJ @PRESENTATION , @SELF_NOM",
                             "@SELF_POSS @BEFORE_ADJ @PRESENTATION @SELF_NOM",
                             "@SELF_POSS @BEFORE_ADJ @PRESENTATION , @SELF_NOM",
                             "@SELF_POSS @BEFORE_ADJ @PRESENTATION CITATION",
                             "@SELF_POSS @BEFORE_ADJ @PRESENTATION SELFCITATION",
                             "@BEFORE_ADJ @PRESENTATION CITATION @SELF_NOM",
                             "@BEFORE_ADJ @PRESENTATION CITATION , @SELF_NOM",
                             "a @BEFORE_ADJ @PRESENTATION CITATION @SELF_NOM",
                             "a @BEFORE_ADJ @PRESENTATION CITATION , @SELF_NOM",
                             "first @PRESENTATION in CITATION",
                             "@PRESENTATION #RR in CITATION",
                             "@PRESENTATION #JJ in CITATION",
                             "@BEFORE_ADJ @CHANGE_NOUN of @SELF_POSS @WORK_NOUN",
                             "@CHANGE on @BEFORE_ADJ @PRESENTATION @PRESENTATION in SELFCITATION",
                             "@CHANGE @BEFORE_ADJ @PRESENTATION @PRESENTATION in SELFCITATION",
                             "@CHANGE @BEFORE_ADJ @PRESENTATION @PRESENTATION in SELFCITATION",
                             "@CHANGE @BEFORE_ADJ @PRESENTATION @PRESENTATION SELFCITATION",
                             "@CHANGE on @SELF_POSS @BEFORE_ADJ @PRESENTATION @PRESENTATION in SELFCITATION",
                             "@CHANGE @SELF_POSS @BEFORE_ADJ @PRESENTATION @PRESENTATION in SELFCITATION",
                             "@CHANGE @SELF_POSS @BEFORE_ADJ @PRESENTATION @PRESENTATION in SELFCITATION",
                             "@CHANGE @SELF_POSS @BEFORE_ADJ @PRESENTATION @PRESENTATION SELFCITATION",
                             "in @SELF_POSS @BEFORE_ADJ @PRESENTATION CITATION",
                             ]
}


AGENT_PATTERNS = {

    "US_AGENT": ["@SELF_NOM",
                 "@SELF_POSS #JJ @WORK_NOUN",
                 "@SELF_POSS #JJ @PRESENTATION_NOUN",
                 "@SELF_POSS #JJ @ARGUMENTATION_NOUN",
                 "@SELF_POSS #JJ @SOLUTION_NOUN",
                 "@SELF_POSS #JJ @RESULT_NOUN",
                 "@SELF_POSS @WORK_NOUN",
                 "@SELF_POSS @PRESENTATION_NOUN",
                 "@SELF_POSS @ARGUMENTATION_NOUN",
                 "@SELF_POSS @SOLUTION_NOUN",
                 "SELF_POSS @RESULT_NOUN",
                 "@WORK_NOUN @GIVEN here",
                 "WORK_NOUN @GIVEN below",
                 "@WORK_NOUN @GIVEN in this @PRESENTATION_NOUN",
                 "@WORK_NOUN @GIVEN in @SELF_POSS @PRESENTATION_NOUN",
                 "the @SOLUTION_NOUN @GIVEN here",
                 "the @SOLUTION_NOUN @GIVEN in this @PRESENTATION_NOUN",
                 "the first author",
                 "the second author",
                 "the third author",
                 "one of the authors",
                 "one of us"],

    "REF_US_AGENT": ["this @PRESENTATION_NOUN",
                     "the present @PRESENTATION_NOUN",
                     "the current @PRESENTATION_NOUN",
                     "the present #JJ @PRESENTATION_NOUN",
                     "the current #JJ @PRESENTATION_NOUN",
                     "the @WORK_NOUN @GIVEN"],

    "OUR_AIM_AGENT": ["@SELF_POSS @AIM_NOUN",
                      "the point of this @PRESENTATION_NOUN",
                      "the @AIM_NOUN of this @PRESENTATION_NOUN",
                      "the @AIM_NOUN of the @GIVEN @WORK_NOUN",
                      "the @AIM_NOUN of @SELF_POSS @WORK_NOUN",
                      "the @AIM_NOUN of @SELF_POSS @PRESENTATION_NOUN",
                      "the most @MAIN_ADJ feature of @SELF_POSS @WORK_NOUN",
                      "contribution of this @PRESENTATION_NOUN",
                      "contribution of the @GIVEN @WORK_NOUN",
                      "contribution of @SELF_POSS @WORK_NOUN",
                      "the question @GIVEN in this PRESENTATION_NOUN",
                      "the question @GIVEN here",
                      "@SELF_POSS @MAIN_ADJ @AIM_NOUN",
                      "@SELF_POSS @AIM_NOUN in this @PRESENTATION_NOUN",
                      "@SELF_POSS @AIM_NOUN here",
                      "the #JJ point of this @PRESENTATION_NOUN",
                      "the #JJ purpose of this @PRESENTATION_NOUN",
                      "the #JJ @AIM_NOUN of this @PRESENTATION_NOUN",
                      "the #JJ @AIM_NOUN of the @GIVEN @WORK_NOUN",
                      "the #JJ @AIM_NOUN of @SELF_POSS @WORK_NOUN",
                      "the #JJ @AIM_NOUN of @SELF_POSS @PRESENTATION_NOUN",
                      "the #JJ question @GIVEN in this PRESENTATION_NOUN",
                      "the #JJ question @GIVEN here"],

    "AIM_REF_AGENT":  ["its @AIM_NOUN",
                       "its #JJ @AIM_NOUN",
                       "@REFERENTIAL #JJ @AIM_NOUN",
                       "contribution of this @WORK_NOUN",
                       "the most important feature of this @WORK_NOUN",
                       "feature of this @WORK_NOUN",
                       "the @AIM_NOUN",
                       "the #JJ @AIM_NOUN"],

    "US_PREVIOUS_AGENT": ["SELFCITATION",
                          "this @BEFORE_ADJ @PRESENTATION_NOUN",
                          "@SELF_POSS @BEFORE_ADJ @PRESENTATION_NOUN",
                          "@SELF_POSS @BEFORE_ADJ @WORK_NOUN",
                          "in CITATION , @SELF_NOM",
                          "in CITATION @SELF_NOM",
                          "the @WORK_NOUN @GIVEN in SELFCITATION",
                          "in @BEFORE_ADJ @PRESENTATION CITATION @SELF_NOM",
                          "in @BEFORE_ADJ @PRESENTATION CITATION , @SELF_NOM",
                          "in a @BEFORE_ADJ @PRESENTATION CITATION @SELF_NOM",
                          "in a @BEFORE_ADJ @PRESENTATION CITATION , @SELF_NOM",
                          ],

    "REF_AGENT": ["@REFERENTIAL #JJ @WORK_NOUN",
                  #"@REFERENTIAL @WORK_NOUN",
                  "this sort of @WORK_NOUN",
                  "this kind of @WORK_NOUN",
                  "this type of @WORK_NOUN",
                  "the current #JJ @WORK_NOUN",
                  "the current @WORK_NOUN",
                  "the @WORK_NOUN",
                  "the @PRESENTATION_NOUN",
                  "the author",
                  "the authors"],

    "THEM_PRONOUN_AGENT": ["@OTHERS_NOM"],

    "THEM_ACTIVE_AGENT": ["CITATION @PRESENTATION"],

    "THEM_AGENT": ["CITATION",
                   "CITATION \"s #NN",
                   "CITATION \"s @PRESENTATION_NOUN",
                   "CITATION \"s @WORK_NOUN",
                   "CITATION \"s @ARGUMENTATION_NOUN",
                   "CITATION \"s #JJ @PRESENTATION_NOUN",
                   "CITATION \"s #JJ @WORK_NOUN",
                   "CITATION \"s #JJ @ARGUMENTATION_NOUN",
                   "the CITATION @WORK_NOUN",
                   "the @WORK_NOUN @GIVEN in CITATION",
                   "the @WORK_NOUN of CITATION",
                   "@OTHERS_POSS @PRESENTATION_NOUN",
                   "@OTHERS_POSS @WORK_NOUN",
                   "@OTHERS_POSS @RESULT_NOUN",
                   "@OTHERS_POSS @ARGUMENTATION_NOUN",
                   "@OTHERS_POSS @SOLUTION_NOUN",
                   "@OTHERS_POSS #JJ @PRESENTATION_NOUN",
                   "@OTHERS_POSS #JJ @WORK_NOUN",
                   "@OTHERS_POSS #JJ @RESULT_NOUN",
                   "@OTHERS_POSS #JJ @ARGUMENTATION_NOUN",
                   "@OTHERS_POSS #JJ @SOLUTION_NOUN"],

    "GAP_AGENT":  ["none of these @WORK_NOUN",
                   "none of those @WORK_NOUN",
                   "no @WORK_NOUN",
                   "no #JJ @WORK_NOUN",
                   "none of these @PRESENTATION_NOUN",
                   "none of those @PRESENTATION_NOUN",
                   "no @PRESENTATION_NOUN",
                   "no #JJ @PRESENTATION_NOUN"],

    "GENERAL_AGENT": ["@TRADITION_ADJ #JJ @WORK_NOUN",
                      "@TRADITION_ADJ use @WORK_NOUN",
                      "@TRADITION_ADJ @WORK_NOUN",
                      "@MANY #JJ @WORK_NOUN",
                      "@MANY @WORK_NOUN",
                      "@BEFORE_ADJ #JJ @WORK_NOUN",
                      "@BEFORE_ADJ @WORK_NOUN",
                      "@BEFORE_ADJ #JJ @PRESENTATION_NOUN",
                      "@BEFORE_ADJ @PRESENTATION_NOUN",
                      "other #JJ @WORK_NOUN",
                      "other @WORK_NOUN",
                      "such @WORK_NOUN",
                      "these #JJ @PRESENTATION_NOUN",
                      "these @PRESENTATION_NOUN",
                      "those #JJ @PRESENTATION_NOUN",
                      "those @PRESENTATION_NOUN",
                      "@REFERENTIAL authors",
                      "@MANY author",
                      "researcher in @DISCIPLINE",
                      "@PROFESSIONALS"],

    "PROBLEM_AGENT": ["@REFERENTIAL #JJ @PROBLEM_NOUN",
                      "@REFERENTIAL @PROBLEM_NOUN",
                      "the @PROBLEM_NOUN"],

    "SOLUTION_AGENT": ["@REFERENTIAL #JJ @SOLUTION_NOUN",
                       "@REFERENTIAL @SOLUTION_NOUN",
                       "the @SOLUTION_NOUN",
                       "the #JJ @SOLUTION_NOUN"],

    "TEXTSTRUCTURE_AGENT": ["@TEXT_NOUN CREF",
                            "@TEXT_NOUN CREF and CREF",
                            "this @TEXT_NOUN",
                            "next @TEXT_NOUN",
                            "next #CD @TEXT_NOUN",
                            "concluding @TEXT_NOUN",
                            "@BEFORE_ADJ @TEXT_NOUN",
                            "@TEXT_NOUN above",
                            "@TEXT_NOUN below",
                            "following @TEXT_NOUN",
                            "remaining @TEXT_NOUN",
                            "subsequent @TEXT_NOUN",
                            "following #CD @TEXT_NOUN",
                            "remaining #CD @TEXT_NOUN",
                            "subsequent #CD @TEXT_NOUN",
                            "@TEXT_NOUN that follow",
                            "rest of this @PRESENTATION_NOUN",
                            "remainder of this @PRESENTATION_NOUN",
                            "in @TEXT_NOUN CREF , @SELF_NOM",
                            "in this @TEXT_NOUN , @SELF_NOM",
                            "in the next @TEXT_NOUN , @SELF_NOM",
                            "in @BEFORE_ADJ @TEXT_NOUN , @SELF_NOM",
                            "in the @BEFORE_ADJ @TEXT_NOUN , @SELF_NOM",
                            "in the @TEXT_NOUN above , @SELF_NOM",
                            "in the @TEXT_NOUN below , @SELF_NOM",
                            "in the following @TEXT_NOUN , @SELF_NOM",
                            "in the remaining @TEXT_NOUN , @SELF_NOM",
                            "in the subsequent @TEXT_NOUN , @SELF_NOM",
                            "in the @TEXT_NOUN that follow , @SELF_NOM",
                            "in the rest of this @PRESENTATION_NOUN , @SELF_NOM",
                            "in the remainder of this @PRESENTATION_NOUN , @SELF_NOM",
                            "below , @SELF_NOM",
                            "the @AIM_NOUN of this @TEXT_NOUN"]
}


AGENT_PATTERNS = {

    'US_AGENT': ['@SELF_NOM',
                 '@SELF_POSS #JJ @WORK_NOUN',
                 '@SELF_POSS #JJ @PRESENTATION_NOUN',
                 '@SELF_POSS #JJ @ARGUMENTATION_NOUN',
                 '@SELF_POSS #JJ @SOLUTION_NOUN',
                 '@SELF_POSS #JJ @RESULT_NOUN',
                 '@SELF_POSS @WORK_NOUN',
                 '@SELF_POSS @PRESENTATION_NOUN',
                 '@SELF_POSS @ARGUMENTATION_NOUN',
                 '@SELF_POSS @SOLUTION_NOUN',
                 'SELF_POSS @RESULT_NOUN',
                 '@WORK_NOUN @GIVEN here',
                 'WORK_NOUN @GIVEN below',
                 '@WORK_NOUN @GIVEN in this @PRESENTATION_NOUN',
                 '@WORK_NOUN @GIVEN in @SELF_POSS @PRESENTATION_NOUN',
                 'the @SOLUTION_NOUN @GIVEN here',
                 'the @SOLUTION_NOUN @GIVEN in this @PRESENTATION_NOUN',
                 'the first author',
                 'the second author',
                 'the third author',
                 'one of the authors',
                 'one of us'],

    'REF_US_AGENT': ['this @PRESENTATION_NOUN',
                     'the present @PRESENTATION_NOUN',
                     'the current @PRESENTATION_NOUN',
                     'the present #JJ @PRESENTATION_NOUN',
                     'the current #JJ @PRESENTATION_NOUN',
                     'the @WORK_NOUN @GIVEN'],

    'OUR_AIM_AGENT': ['@SELF_POSS @AIM_NOUN',
                      'the point of this @PRESENTATION_NOUN',
                      'the @AIM_NOUN of this @PRESENTATION_NOUN',
                      'the @AIM_NOUN of the @GIVEN @WORK_NOUN',
                      'the @AIM_NOUN of @SELF_POSS @WORK_NOUN',
                      'the @AIM_NOUN of @SELF_POSS @PRESENTATION_NOUN',
                      'the most @MAIN_ADJ feature of @SELF_POSS @WORK_NOUN',
                      'contribution of this @PRESENTATION_NOUN',
                      'contribution of the @GIVEN @WORK_NOUN',
                      'contribution of @SELF_POSS @WORK_NOUN',
                      'the question @GIVEN in this PRESENTATION_NOUN',
                      'the question @GIVEN here',
                      '@SELF_POSS @MAIN_ADJ @AIM_NOUN',
                      '@SELF_POSS @AIM_NOUN in this @PRESENTATION_NOUN',
                      '@SELF_POSS @AIM_NOUN here',
                      'the #JJ point of this @PRESENTATION_NOUN',
                      'the #JJ purpose of this @PRESENTATION_NOUN',
                      'the #JJ @AIM_NOUN of this @PRESENTATION_NOUN',
                      'the #JJ @AIM_NOUN of the @GIVEN @WORK_NOUN',
                      'the #JJ @AIM_NOUN of @SELF_POSS @WORK_NOUN',
                      'the #JJ @AIM_NOUN of @SELF_POSS @PRESENTATION_NOUN',
                      'the #JJ question @GIVEN in this PRESENTATION_NOUN',
                      'the #JJ question @GIVEN here'],

    'AIM_REF_AGENT':  ['its @AIM_NOUN',
                       'its #JJ @AIM_NOUN',
                       '@REFERENTIAL #JJ @AIM_NOUN',
                       'contribution of this @WORK_NOUN',
                       'the most important feature of this @WORK_NOUN',
                       'feature of this @WORK_NOUN',
                       'the @AIM_NOUN',
                       'the #JJ @AIM_NOUN'],

    'US_PREVIOUS_AGENT': ['SELFCITATION',
                          'this @BEFORE_ADJ @PRESENTATION_NOUN',
                          '@SELF_POSS @BEFORE_ADJ @PRESENTATION_NOUN',
                          '@SELF_POSS @BEFORE_ADJ @WORK_NOUN',
                          'in CITATION , @SELF_NOM',
                          'in CITATION @SELF_NOM',
                          'the @WORK_NOUN @GIVEN in SELFCITATION',
                          'in @BEFORE_ADJ @PRESENTATION CITATION @SELF_NOM',
                          'in @BEFORE_ADJ @PRESENTATION CITATION , @SELF_NOM',
                          'in a @BEFORE_ADJ @PRESENTATION CITATION @SELF_NOM',
                          'in a @BEFORE_ADJ @PRESENTATION CITATION , @SELF_NOM',
                          ],

    'REF_AGENT': ['@REFERENTIAL #JJ @WORK_NOUN',
                  #'@REFERENTIAL @WORK_NOUN',
                  'this sort of @WORK_NOUN',
                  'this kind of @WORK_NOUN',
                  'this type of @WORK_NOUN',
                  'the current #JJ @WORK_NOUN',
                  'the current @WORK_NOUN',
                  'the @WORK_NOUN',
                  'the @PRESENTATION_NOUN',
                  'the author',
                  'the authors'],

    'THEM_PRONOUN_AGENT': ['@OTHERS_NOM'],

    'THEM_ACTIVE_AGENT': ['CITATION @PRESENTATION'],

    'THEM_AGENT': ['CITATION',
                   'CITATION \'s #NN',
                   'CITATION \'s @PRESENTATION_NOUN',
                   'CITATION \'s @WORK_NOUN',
                   'CITATION \'s @ARGUMENTATION_NOUN',
                   'CITATION \'s #JJ @PRESENTATION_NOUN',
                   'CITATION \'s #JJ @WORK_NOUN',
                   'CITATION \'s #JJ @ARGUMENTATION_NOUN',
                   'the CITATION @WORK_NOUN',
                   'the @WORK_NOUN @GIVEN in CITATION',
                   'the @WORK_NOUN of CITATION',
                   '@OTHERS_POSS @PRESENTATION_NOUN',
                   '@OTHERS_POSS @WORK_NOUN',
                   '@OTHERS_POSS @RESULT_NOUN',
                   '@OTHERS_POSS @ARGUMENTATION_NOUN',
                   '@OTHERS_POSS @SOLUTION_NOUN',
                   '@OTHERS_POSS #JJ @PRESENTATION_NOUN',
                   '@OTHERS_POSS #JJ @WORK_NOUN',
                   '@OTHERS_POSS #JJ @RESULT_NOUN',
                   '@OTHERS_POSS #JJ @ARGUMENTATION_NOUN',
                   '@OTHERS_POSS #JJ @SOLUTION_NOUN'],

    'GAP_AGENT':  ['none of these @WORK_NOUN',
                   'none of those @WORK_NOUN',
                   'no @WORK_NOUN',
                   'no #JJ @WORK_NOUN',
                   'none of these @PRESENTATION_NOUN',
                   'none of those @PRESENTATION_NOUN',
                   'no @PRESENTATION_NOUN',
                   'no #JJ @PRESENTATION_NOUN'],

    'GENERAL_AGENT': ['@TRADITION_ADJ #JJ @WORK_NOUN',
                      '@TRADITION_ADJ use @WORK_NOUN',
                      '@TRADITION_ADJ @WORK_NOUN',
                      '@MANY #JJ @WORK_NOUN',
                      '@MANY @WORK_NOUN',
                      '@BEFORE_ADJ #JJ @WORK_NOUN',
                      '@BEFORE_ADJ @WORK_NOUN',
                      '@BEFORE_ADJ #JJ @PRESENTATION_NOUN',
                      '@BEFORE_ADJ @PRESENTATION_NOUN',
                      'other #JJ @WORK_NOUN',
                      'other @WORK_NOUN',
                      'such @WORK_NOUN',
                      'these #JJ @PRESENTATION_NOUN',
                      'these @PRESENTATION_NOUN',
                      'those #JJ @PRESENTATION_NOUN',
                      'those @PRESENTATION_NOUN',
                      '@REFERENTIAL authors',
                      '@MANY author',
                      'researcher in @DISCIPLINE',
                      '@PROFESSIONALS'],

    'PROBLEM_AGENT': ['@REFERENTIAL #JJ @PROBLEM_NOUN',
                      '@REFERENTIAL @PROBLEM_NOUN',
                      'the @PROBLEM_NOUN'],

    'SOLUTION_AGENT': ['@REFERENTIAL #JJ @SOLUTION_NOUN',
                       '@REFERENTIAL @SOLUTION_NOUN',
                       'the @SOLUTION_NOUN',
                       'the #JJ @SOLUTION_NOUN'],

    'TEXTSTRUCTURE_AGENT': ['@TEXT_NOUN CREF',
                            '@TEXT_NOUN CREF and CREF',
                            'this @TEXT_NOUN',
                            'next @TEXT_NOUN',
                            'next #CD @TEXT_NOUN',
                            'concluding @TEXT_NOUN',
                            '@BEFORE_ADJ @TEXT_NOUN',
                            '@TEXT_NOUN above',
                            '@TEXT_NOUN below',
                            'following @TEXT_NOUN',
                            'remaining @TEXT_NOUN',
                            'subsequent @TEXT_NOUN',
                            'following #CD @TEXT_NOUN',
                            'remaining #CD @TEXT_NOUN',
                            'subsequent #CD @TEXT_NOUN',
                            '@TEXT_NOUN that follow',
                            'rest of this @PRESENTATION_NOUN',
                            'remainder of this @PRESENTATION_NOUN',
                            'in @TEXT_NOUN CREF , @SELF_NOM',
                            'in this @TEXT_NOUN , @SELF_NOM',
                            'in the next @TEXT_NOUN , @SELF_NOM',
                            'in @BEFORE_ADJ @TEXT_NOUN , @SELF_NOM',
                            'in the @BEFORE_ADJ @TEXT_NOUN , @SELF_NOM',
                            'in the @TEXT_NOUN above , @SELF_NOM',
                            'in the @TEXT_NOUN below , @SELF_NOM',
                            'in the following @TEXT_NOUN , @SELF_NOM',
                            'in the remaining @TEXT_NOUN , @SELF_NOM',
                            'in the subsequent @TEXT_NOUN , @SELF_NOM',
                            'in the @TEXT_NOUN that follow , @SELF_NOM',
                            'in the rest of this @PRESENTATION_NOUN , @SELF_NOM',
                            'in the remainder of this @PRESENTATION_NOUN , @SELF_NOM',
                            'below , @SELF_NOM',
                            'the @AIM_NOUN of this @TEXT_NOUN']
}
